# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/8"

  config.vm.define "centos1" do |centos|
    centos.vm.hostname = "centos1"
    config.vm.disk :disk, size: "2GB", name: "extra_storage1"
    config.vm.disk :disk, size: "1GB", name: "extra_storage2"
    
    centos.vm.provider "virtualbox" do |vb|
      vb.name = "centos1"
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end
end
